In [6]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\EELU\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [2]:
df = pd.read_csv("deceptive-opinion.csv")

In [3]:
df.head()

,deceptive,hotel,polarity,source,text
0,truthful,conrad,positive,TripAdvisor,We stayed for a one night getaway with family ...
1,truthful,hyatt,positive,TripAdvisor,Triple A rate with upgrade to view room was le...
2,truthful,hyatt,positive,TripAdvisor,This comes a little late as I'm finally catchi...
3,truthful,omni,positive,TripAdvisor,The Omni Chicago really delivers on all fronts...
4,truthful,hyatt,positive,TripAdvisor,I asked for a high floor away from the elevato...

In [4]:
df.isnull().sum()

deceptive    0
hotel        0
polarity     0
source       0
text         0
dtype: int64

In [5]:
df.shape

(1600, 5)

In [ ]:
def clean_text(text):
    text = text.replace(',', '')
    text = text.lower() 
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return ' '.join(words)

df['text'] = df['text'].apply(clean_text)

In [10]:
df

,deceptive,hotel,polarity,source,text
0,truthful,conrad,positive,TripAdvisor,stayed one night getaway family thursday. trip...
1,truthful,hyatt,positive,TripAdvisor,triple rate upgrade view room less $200 also i...
2,truthful,hyatt,positive,TripAdvisor,comes little late finally catching reviews pas...
3,truthful,omni,positive,TripAdvisor,omni chicago really delivers fronts spaciousne...
4,truthful,hyatt,positive,TripAdvisor,asked high floor away elevator got. room pleas...
...,...,...,...,...,...
1595,deceptive,intercontinental,negative,MTurk,problems started booked intercontinental chica...
1596,deceptive,amalfi,negative,MTurk,amalfi hotel beautiful website interior decora...
1597,deceptive,intercontinental,negative,MTurk,intercontinental chicago magnificent mile outs...
1598,deceptive,palmer,negative,MTurk,palmer house hilton looks good pictures outsid...
1599,deceptive,amalfi,negative,MTurk,former chicagoan appalled amalfi hotel chicago...